[workspace]
resolver = "2"
members = []

[workspace.dependencies]
vlcrs-macros = { path = "../src/rust/vlcrs-macros" }
vlcrs-messages = { path = "../src/rust/vlcrs-messages" }
vlcrs-plugin = { path = "../src/rust/vlcrs-plugin" }
